se agrego el servicio que retorna las categorias
gdepina/superdwn pull request #17
Opened 2022-07-28 21:41 UTC by argsprite

Se agregó el servicio para obtener un array con las categorías de los productos.

2022-07-28 21:44 UTC, gdepina requested changes

2022-07-28 21:44 UTC, gdepina commented on package.json
> +    "nodemon": "^1.17.3",
x q cambiaste el tipo de version de nodemon?

2022-07-28 21:44 UTC, gdepina commented on server/controllers/product.js
> +  ProductModel.distinct('category', function (err, result) {
en todos lados usamos arrow functions por un tema de consistencia haria lo mismo en todos lados.

2022-07-28 21:53 UTC, argsprite commented on package.json
> +    "nodemon": "^1.17.3",
Hola German.
Cuando quise runear el development me aparecía la leyenda de: "nodemon" no se reconoce como un comando interno o externo, programa o archivo por lotes ejecutable.
Lo que hice fue hacer un: npm i nodemon
Y con eso pude correr el dev.

2022-07-28 22:03 UTC, argsprite commented on server/controllers/product.js
> +  ProductModel.distinct('category', function (err, result) {
Muchas Gracias por la recomendacion, una consulta, tengo que editar el archivo de nuevo para aplicar esos cambios o solo tenerlo en cuenta para el proximo PR?

2022-07-29 02:51 UTC, gdepina approved these changes

2022-07-29 02:51 UTC, merged