hicimos el servicio de profile
gdepina/superdwn pull request #19
Opened 2022-07-29 18:34 UTC by remifu93

2022-07-29 19:39 UTC, gdepina requested changes

2022-07-29 19:39 UTC, gdepina commented on server/controllers/user.js
> +    UserModel.findOne({userName}, ['name', 'surname', 'email'], (err, user) => {
creo que aca falta el avatar para poder mostrar la foto del usuario y quizas tambien la fecha de nacimiento asi le calculamos la edad y hacemos un perfil fancy.

2022-07-29 19:39 UTC, gdepina commented on server/controllers/user.js
> +        !user ? res.status(404).send('no existe el usuario') : res.json(user)
vamos a usar todas las respuestas de error y no error en formato json para que el FE pueda manejarlo y mapearlo a un feedback lindo de esta forma el FE no puede atrapar la respuesta de forma sencilla.

2022-07-29 19:39 UTC, gdepina commented on server/routes/user.js
>  import auth from '../controllers/auth';
estoy ok en cambiar UserController por User, pero User esta mayuscula y auth no?, deberíamos tener un criterio consistente pondría Auth.

2022-07-29 19:39 UTC, gdepina commented on server/routes/user.js
> +router.get('/api/users/:userName', User.find)
esta ruta no debería ser privada? agregar middleware de auth

2022-07-30 15:03 UTC, remifu93 commented on server/controllers/user.js
> +    UserModel.findOne({userName}, ['name', 'surname', 'email'], (err, user) => {
![image](https://user-images.githubusercontent.com/84943791/181920186-339038f2-fd23-4d4c-bc22-e31a3e6a14a6.png)
implemente al create de usuarios la funcion para subir avatar, en el controllador de ver perfil de un determinado usuario devuelvo el avatar.data y me devuelve el buffer no se si esta bien eso, ahora pusheo y me lo revisas porfa

2022-07-30 15:06 UTC, remifu93 commented on server/controllers/user.js
> +        !user ? res.status(404).send('no existe el usuario') : res.json(user)
`if (err) res.status(500).send("internal server error")` implementado de ahora en mas

2022-07-30 15:06 UTC, remifu93 commented on server/routes/user.js
>  import auth from '../controllers/auth';
corregido no vuelve a pasar

2022-07-30 18:10 UTC, gdepina requested changes

2022-07-30 18:10 UTC, gdepina commented on server/controllers/user.js
> +    UserModel.findOne(query, {_id:0, password: 0}, (err, user) => {
es necesario que aca este el password?, ademas no lo estas enviando nunca, eso lo q hace es q find one te retorne id y password, esta raro o  no lo entiendo.

2022-07-30 18:10 UTC, gdepina commented on server/routes/user.js
> +router.get('/api/user/profile/', Auth.isLogged, User.find)
este servicio no lo entendi como vas a buscar un perfil sin saber cual es el usuario?

2022-07-30 18:10 UTC, gdepina commented on server/controllers/user.js
> +    let form = new Formidable.IncomingForm()
esto ta cheto

2022-07-31 00:50 UTC, remifu93 commented on server/routes/user.js
> +router.get('/api/user/profile/', Auth.isLogged, User.find)
tieniendo en cuenta que el middleware comprueba si el usuario esta enviando un token (usamos el id del usuario como token). El servicio de profile lo que hace es detectar si le estamos pasando o no un parametro por url en /user/profile/:username si encuentra el username devuelve el perfil de ese usuario, de lo contrario devuelve el perfil del usuario que esta logueado en la ruta user/profile

2022-08-01 15:37 UTC, gdepina approved these changes

2022-08-01 15:37 UTC, merged