Se agrego que cuando apretas el btn de register te sale el el formula…
gdepina/superdwn pull request #30
Opened 2022-08-19 21:31 UTC by argsprite

…rio de registro y la ruta a ese formulario

2022-08-24 14:46 UTC, gdepina requested changes

2022-08-24 14:46 UTC, gdepina commented on package.json
> +    "dayjs": "^1.11.5",
esto x q lo agrgas no veo q lo uses?

2022-08-24 14:59 UTC, argsprite commented on package.json
> +    "dayjs": "^1.11.5",
Hola Rey.

Eso lo bajo la librería de @mantine/dates

dejo una captura por las dudas
![imagen](https://user-images.githubusercontent.com/76662469/186452303-d4ea7ad0-3a50-4ab1-adf9-e7bc171330f8.png)

2022-08-24 18:34 UTC, santiagodale approved these changes

2022-08-25 08:59 UTC, remifu93 approved these changes

2022-08-26 20:35 UTC, gdepina approved these changes

2022-08-26 20:35 UTC, gdepina commented on client/components/Register/Register.js
> +      {/* <Card.Section> */}
si no usas section borralo

2022-08-26 20:35 UTC, merged